version: '3.9'
services:
  db:
    container_name: db
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - './mongo/db:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
